### ISSUE TITLE
Investigate intermittent flashing

### ISSUE THREAD

**Issue by aib** [aib/opi2g-utils#1]
Flashing seems to succeed intermittently. Some findings:

The attempt AFTER a failed attempt with a modified pdl2 seems to succeed.
This is regardless of whether we inject a partition table into bootloader.bin.
It also doesn't seem to matter whether we send an image list prior to flashing.

**Comment by aib** [comment]
The indicator of success seems to be:

mtdparts_ptbl_read: load partition table from 0xc000
partition table: mtdparts=rda_nand:2M@0(bootloader),510M(nandroot)

right after the PDL2 boot (on the attempt after a failed one with a modified pdl2), before we send anything.

**Comment by aib** [comment]
Repetitive attempts with the modified pdl2 succeed (after the first failure). The success indicator seems to work in these cases, too.

**Comment by aib** [comment]
Adding a second PDL2 (so a third PDL) stage doesn't work. The third PDL boots without the success indicator and fails.

A regular attempt after power cycling, however, succeeds, if PDL3 is a modified pdl2. The success indicator is also present.

**Comment by aib** [comment]
The result of READ_PARTITION_TABLE seems to mirror the success indicator, hence eebf2b2c4461fb8e12bbfc360b550822183e60a6

**Comment by aib** [comment]
Ultimately, find_dev_and_part() is used by START_DATA

**Comment by txurtxil** [comment]
Thanks for your work, i will try it

**Comment by aib** [comment]
mtdparts_init_from_ptbl() would load a bootloader-injected partition table (@0xc000), but it's only called at pdl2 startup.

mtdparts_init_default() falls back to MTDPARTS_DEFAULT define in source and is called at startup and in FORMAT_FLASH.

**Comment by aib** [comment]
Yes!
Formatting the flash causes the partition table in PDL2 to be read and used immediately, as opposed to the next boot. So we 62d0ee65520092829b238bcd6536f79f06763263

**Comment by aib** [comment]
Partition table in(ter)jection + FORMAT_FLASH does not work

**Comment by aib** [comment]
Merely booting a modified pdl2 does not cause the next boot to use the correct (modified) partition table. The "bootloader" partition must be written in order for the partition table to be changed on the next boot. Writing a different partition does not seem to work.

**Comment by aib** [comment]
Normally "mtdparts default" is called in PREBOOT. While this seems to set up the partitions according the environment variable, it does not help with flashing.

**Comment by aib** [comment]
Solution: Either modify PDL2 to skip/ignore `mtdparts_init_from_ptbl` and call `mtdparts_init_default` at init, or use `--format-flash`.

**Comment by raimundo151179** [comment]
there is a datasheet to see all the 2g IoT info.
[386cd004-3df5-48aa-9567-2f111779377e.pdf](https://github.com/aib/opi2g-utils/files/1232725/386cd004-3df5-48aa-9567-2f111779377e.pdf)

**Comment by aib** [comment]
Ah, thank you @raimundo151179 . Though my problem was with the PDL code, specifically it having 3+ different ideas of where the MTD partition table should be stored. It's all good now and my flasher seems to be working (with a custom PDL2).

**Comment by raimundo151179** [comment]
I have a question, you post 2 code files .py, I want to know if it is possible to change the android boot by linux, I want to install linuex instead android into the flash.

Thanks.

**Comment by aib** [comment]
@raimundo151179 Yes, it is possible, but the process is a bit convoluted. I'm not sure where the best place to document it might be, but I'll open another issue for it... #2
