### ISSUE TITLE
The script stuck at "Opening /dev/ttyACM0 ..." 

### ISSUE THREAD

**Issue by kprasadvnsi** [aib/opi2g-utils#4]
the device shows up as 

kp@Vostro-2420:~/$ dmesg | grep ttyACM0
[15741.824524] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device
[16185.771067] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device
[16514.730308] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device
[16623.990393] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device
[16860.657857] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device
[17041.701594] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device

is there any way to know whats going on ??

**Comment by aib** [comment]
I had the same thing happen to me but it went away after I fiddled with the USB cable and restarted the device. Is your problem reproducible?

If so, can you post an strace? (Just prefix your command with `strace`.)

**Comment by kprasadvnsi** [comment]
Nand write is fine on windows with OrangePi_2G-IOT_Update Tool so hardware setup is not the problem here,  what i think is my Python installation may have some problem. 

I will try to come up with a C Implementation of the same.

**Comment by aib** [comment]
I had the same problem with the very same setup that let me flash the device successfully a couple of times. It turned out to be a loose connection.

...I think. I haven't been able to duplicate the error since.

An strace would really be helpful. It's the open() call to the serial port that was blocking if I remember correctly.

The script should also work on Windows, by the way.

**Comment by kprasadvnsi** [comment]
The script is working on windows. and with the linux, i have managed to find the function that got blocked in script. at Line No: 281 "tag = interface.read(1)"

I have tried strace as well, but the output is too long 1127 lines and i dont know where to look for the problem. 

[log.txt](https://github.com/aib/opi2g-utils/files/1283566/log.txt)

**Comment by aib** [comment]
Hmm, it looks like you're receiving no response to the initial CONNECT command. I have no idea what might cause this. Do you have output from the device's serial console, by any chance?

(By the way you can pass `-v -v` to the script to make it more verbose. I think in this case it would confirm that there's no response to the first CONNECT command.)

**Comment by jhonoryza** [comment]
i solved this problem by reinstall the linux
