### ISSUE TITLE
dead website

### ISSUE THREAD

**Issue by clach04** [aib/opi2g-utils#9]
Do you have a copy of the article linked in the readme; https://www.aib42.net/article/hacking-orangepi-2g ? Archive.org does not :(

**Comment by aib** [comment]
It's back up at https://www.aib.link/article/hacking-orangepi-2g .

For reference, it's created by the repository at https://github.com/aib/www.aib42.net .

**Comment by clach04** [comment]
Thanks! I submitted a save to archive,  https://web.archive.org/web/20220411170832/https://www.aib.link/article/hacking-orangepi-2g

I don't have a board but was thinking about getting one for a project and was really interested in booting a mini linux dist from nand. Thanks for sharing 👍
